version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:3000"
        #      - "80:80"
    container_name: "web_Vlearn"
    volumes:
      - ./app/:/app
    restart: unless-stopped
