version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    container_name: "VlearnReact"
    volumes:
      - ./app/:/app
        #    restart: unless-stopped
